name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master", "release" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
     #从 Secrets 还原 keystore 文件
    - name: Restore keystore file
      env:
        KEYSTORE_BASE64: ${{ secrets.APK_SIGN_JKS }}
      run: |
        echo $KEYSTORE_BASE64 | base64 -d > sign_keystore.jks
      working-directory: ./sign/android
    - name: Create sign.properties
      run: |
        echo "storeFile=sign_keystore.jks" > key.properties
        echo "storePassword=${{ secrets.APK_SIGN_KEYSTORE_PASSWORD }}" >> key.properties
        echo "keyAlias=${{ secrets.APK_SIGN_ALIAS }}" >> key.properties
        echo "keyPassword=${{ secrets.APK_SIGN_PASSWORD }}" >> key.properties
      working-directory: ./sign/android
    - name: Build Android APK
      run: ./gradlew clean :androidApp:assembleProdRelease
    # 读取安卓版本号，用于产物命名
    - name: Get app version
      id: get_version
      run: |
        # 从build.gradle中提取versionName（适配大多数安卓项目）
        VERSION=$(grep "versionName" androidApp/build.gradle.kts | head -1 | awk -F '"' '{print $2}')
        echo "APP_VERSION=$VERSION" >> $GITHUB_OUTPUT
    # 上传保存产物
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: wxpusher-app-v${{ steps.get_version.outputs.APP_VERSION }}-prod-${{ github.run_id }}.apk
        path: androidApp/build/outputs/apk/prod/release/wxpusher-app-*.apk